services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.fe
    ports:
      - ${PORT}:80
    develop:
      watch:
        - action: rebuild
          path: ./packages/fe
        - action: rebuild
          path: ./packages/utils
        - action: rebuild
          path: package.json

  backend:
    build:
      context: .
      dockerfile: Dockerfile.be
    develop:
      watch:
        - action: rebuild
          path: ./packages/be
        - action: rebuild
          path: ./packages/utils
        - action: rebuild
          path: package.json
