# version: "3"
services:
  backend:
    image: "compose-test/backend"
    build:
      context: ./packages/be
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          service: backend
          files:
            - ./packages/be/src
  frontend:
    image: "compose-test/frontend"
    build:
      context: ./packages/fe
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    links:
      - backend
    develop:
      watch:
        - action: rebuild
          service: frontend
          files:
            - ./packages/fe/src
