# Use a Node.js image matching your workspace's Node.js version
FROM node:alpine as build

WORKDIR /usr/src/app


COPY package*.json ./
COPY ./packages/fe ./packages/fe
COPY ./packages/utils ./packages/utils

RUN npm install

RUN npm run build

FROM nginx:alpine

COPY --from=build /usr/src/app/packages/fe/public /etc/nginx/html
COPY ./packages/fe/nginx/nginx.conf /etc/nginx/conf.d/default.conf
